### ISSUE TITLE
Leslie Lamport, “Time, Clocks, and the Ordering of Events in a Distributed System”

### ISSUE THREAD

**Issue by hmadkhali** [lkuper/CSE232-2020-10#5]
The scribes are: 

@cluelessbasu 
@andavid0 
@bosdhill 
@versey-sherry 
@lakshmikrish-97 

Thanks

**Comment by lakshmikrish-97** [comment]
closing this issue, as there is another one opened already - please let me know if this okay

**Comment by hmadkhali** [comment]
ok
________________________________
